blank_issues_enabled: false
contact_links:
  - name: ğŸ†• Feature Request
    url: https://github.com/AllTheMods/All-the-mods-10-Sky/discussions/categories/modpack-content
    about: "Create a discussion about your new feature/suggestion"
  - name: "â“ I don't know, I just need help"
    url: https://discord.gg/allthemods
    about: "Join our Discord channel: #10sky-techsupport"
