#Base energy storage in Joules of: Heat Generator
# Default: 160000
# Range: 1 ~ 9223372036854775807
heatGenerator = 320000
#Base energy storage in Joules of: Bio-Generator
# Default: 160000
# Range: 1 ~ 9223372036854775807
bioGenerator = 320000
#Base energy storage in Joules of: Solar Generator
# Default: 96000
# Range: 1 ~ 9223372036854775807
solarGenerator = 192000
#Base energy storage in Joules of: Advanced Solar Generator
# Default: 200000
# Range: 1 ~ 9223372036854775807
advancedSolarGenerator = 400000
#Base energy storage in Joules of: Wind Generator
# Default: 200000
# Range: 1 ~ 9223372036854775807
windGenerator = 400000
