#Energy per operation in Joules of: Enrichment Chamber
# Default: 50
# Range: 0 ~ 9223372036854775807
enrichmentChamber = 100
#Energy per operation in Joules of: Osmium Compressor
# Default: 100
# Range: 0 ~ 9223372036854775807
osmiumCompressor = 200
#Energy per operation in Joules of: Combiner
# Default: 50
# Range: 0 ~ 9223372036854775807
combiner = 100
#Energy per operation in Joules of: Crusher
# Default: 50
# Range: 0 ~ 9223372036854775807
crusher = 100
#Energy per operation in Joules of: Metallurgic Infuser
# Default: 50
# Range: 0 ~ 9223372036854775807
metallurgicInfuser = 100
#Energy per operation in Joules of: Purification Chamber
# Default: 200
# Range: 0 ~ 9223372036854775807
purificationChamber = 400
#Energy per operation in Joules of: Energized Smelter
# Default: 50
# Range: 0 ~ 9223372036854775807
energizedSmelter = 100
#Energy per operation in Joules of: Digital Miner
# Default: 1000
# Range: 0 ~ 9223372036854775807
digitalMiner = 1000
#Energy per operation in Joules of: Electric Pump
# Default: 100
# Range: 0 ~ 9223372036854775807
electricPump = 200
#Energy in Joules that can be transferred at once per charge operation.
# Default: 1024000
# Range: 0 ~ 9223372036854775807
chargepad = 2048000
#Energy per operation in Joules of: Rotary Condensentrator
# Default: 50
# Range: 0 ~ 9223372036854775807
rotaryCondensentrator = 100
#Energy per operation in Joules of: Chemical Oxidizer
# Default: 200
# Range: 0 ~ 9223372036854775807
chemicalOxidizer = 400
#Energy per operation in Joules of: Chemical Infuser
# Default: 200
# Range: 0 ~ 9223372036854775807
chemicalInfuser = 400
#Energy per operation in Joules of: Chemical Injection Chamber
# Default: 400
# Range: 0 ~ 9223372036854775807
chemicalInjectionChamber = 800
#Energy per operation in Joules of: Precision Sawmill
# Default: 50
# Range: 0 ~ 9223372036854775807
precisionSawmill = 100
#Energy per operation in Joules of: Chemical Dissolution Chamber
# Default: 400
# Range: 0 ~ 9223372036854775807
chemicalDissolutionChamber = 800
#Energy per operation in Joules of: Chemical Washer
# Default: 200
# Range: 0 ~ 9223372036854775807
chemicalWasher = 400
#Energy per operation in Joules of: Chemical Crystallizer
# Default: 400
# Range: 0 ~ 9223372036854775807
chemicalCrystallizer = 800
#Energy per operation in Joules of: Seismic Vibrator
# Default: 50
# Range: 0 ~ 9223372036854775807
seismicVibrator = 100
#Energy per operation in Joules of: Pressurized Reaction Chamber
# Default: 5
# Range: 0 ~ 9223372036854775807
pressurizedReactionBase = 10
#Energy per operation in Joules of: Fluidic Plenisher
# Default: 100
# Range: 0 ~ 9223372036854775807
fluidicPlenisher = 200
#Energy per operation in Joules of: Laser
# Default: 10000
# Range: 0 ~ 9223372036854775807
laser = 40000
#Energy per operation in Joules of: Formulaic Assemblicator
# Default: 100
# Range: 0 ~ 9223372036854775807
formulaicAssemblicator = 400
#Energy per operation in Joules of: Modification Station
# Default: 400
# Range: 0 ~ 9223372036854775807
modificationStation = 400
#Energy per operation in Joules of: Isotopic Centrifuge
# Default: 200
# Range: 0 ~ 9223372036854775807
isotopicCentrifuge = 400
#Energy per operation in Joules of: Nutritional Liquifier
# Default: 200
# Range: 0 ~ 9223372036854775807
nutritionalLiquifier = 400
#Energy per operation in Joules of: Nucleosynthesizer
# Default: 100000
# Range: 0 ~ 9223372036854775807
antiprotonicNucleosynthesizer = 100000
#Energy per operation in Joules of: Pigment Extractor
# Default: 200
# Range: 0 ~ 9223372036854775807
pigmentExtractor = 400
#Energy per operation in Joules of: Pigment Mixer
# Default: 200
# Range: 0 ~ 9223372036854775807
pigmentMixer = 400
#Energy per operation in Joules of: Painting Machine
# Default: 100
# Range: 0 ~ 9223372036854775807
paintingMachine = 400
#Energy per chunk per tick in Joules.
# Default: 5000
# Range: 0 ~ 9223372036854775807
dimensionalStabilizer = 10000
#If enabled, Chemical Injectors and Purification Chambers will consume a semi randomized amount of chemical each operation.
randomizedConsumption = false

#Settings for configuring Teleporter Energy Usage
[teleporter]
	#Base cost in Joules for teleporting an entity.
	# Default: 1000
	# Range: 0 ~ 9223372036854775807
	base = 4000
	#Joules per unit of distance travelled during teleportation - sqrt(xDiff^2 + yDiff^2 + zDiff^2).
	# Default: 10
	# Range: 0 ~ 9223372036854775807
	distance = 12
	#Flat additional cost for interdimensional teleportation. Distance is still taken into account minimizing energy cost based on dimension scales.
	# Default: 10000
	# Range: 0 ~ 9223372036854775807
	dimensionPenalty = 80000
