#Base energy storage in Joules of: Enrichment Chamber
# Default: 20000
# Range: 1 ~ 9223372036854775807
enrichmentChamber = 80000
#Base energy storage in Joules of: Osmium Compressor
# Default: 80000
# Range: 1 ~ 9223372036854775807
osmiumCompressor = 320000
#Base energy storage in Joules of: Combiner
# Default: 40000
# Range: 1 ~ 9223372036854775807
combiner = 160000
#Base energy storage in Joules of: Crusher
# Default: 20000
# Range: 1 ~ 9223372036854775807
crusher = 80000
#Base energy storage in Joules of: Metallurgic Infuser
# Default: 20000
# Range: 1 ~ 9223372036854775807
metallurgicInfuser = 80000
#Base energy storage in Joules of: Purification Chamber
# Default: 80000
# Range: 1 ~ 9223372036854775807
purificationChamber = 320000
#Base energy storage in Joules of: Energized Smelter
# Default: 20000
# Range: 1 ~ 9223372036854775807
energizedSmelter = 80000
#Base energy storage in Joules of: Digital Miner
# Default: 50000
# Range: 1 ~ 9223372036854775807
digitalMiner = 200000
#Base energy storage in Joules of: Electric Pump
# Default: 40000
# Range: 1 ~ 9223372036854775807
electricPump = 160000
#Base energy storage in Joules of: Chargepad
# Default: 2048000
# Range: 1 ~ 9223372036854775807
chargepad = 8192000
#Base energy storage in Joules of: Rotary Condensentrator
# Default: 20000
# Range: 1 ~ 9223372036854775807
rotaryCondensentrator = 80000
#Base energy storage in Joules of: Chemical Oxidizer
# Default: 80000
# Range: 1 ~ 9223372036854775807
chemicalOxidizer = 320000
#Base energy storage in Joules of: Chemical Infuser
# Default: 80000
# Range: 1 ~ 9223372036854775807
chemicalInfuser = 320000
#Base energy storage in Joules of: Chemical Injection Chamber
# Default: 160000
# Range: 1 ~ 9223372036854775807
chemicalInjectionChamber = 640000
#Base energy storage in Joules of: Electrolytic Separator
# Default: 160000
# Range: 1 ~ 9223372036854775807
electrolyticSeparator = 640000
#Base energy storage in Joules of: Precision Sawmill
# Default: 20000
# Range: 1 ~ 9223372036854775807
precisionSawmill = 80000
#Base energy storage in Joules of: Chemical Dissolution Chamber
# Default: 160000
# Range: 1 ~ 9223372036854775807
chemicalDissolutionChamber = 640000
#Base energy storage in Joules of: Chemical Washer
# Default: 80000
# Range: 1 ~ 9223372036854775807
chemicalWasher = 320000
#Base energy storage in Joules of: Chemical Crystallizer
# Default: 160000
# Range: 1 ~ 9223372036854775807
chemicalCrystallizer = 640000
#Base energy storage in Joules of: Seismic Vibrator
# Default: 20000
# Range: 1 ~ 9223372036854775807
seismicVibrator = 80000
#Base energy storage in Joules of: Pressurized Reaction Chamber
# Default: 2000
# Range: 1 ~ 9223372036854775807
pressurizedReactionBase = 8000
#Base energy storage in Joules of: Fluidic Plenisher
# Default: 40000
# Range: 1 ~ 9223372036854775807
fluidicPlenisher = 160000
#Base energy storage in Joules of: Laser
# Default: 2000000
# Range: 1 ~ 9223372036854775807
laser = 8000000
#Base energy storage in Joules of: Laser Amplifier
# Default: 5000000000
# Range: 1 ~ 9223372036854775807
laserAmplifier = 20000000000
#Base energy storage in Joules of: Laser Tractor Beam
# Default: 5000000000
# Range: 1 ~ 9223372036854775807
laserTractorBeam = 20000000000
#Base energy storage in Joules of: Formulaic Assemblicator
# Default: 40000
# Range: 1 ~ 9223372036854775807
formulaicAssemblicator = 160000
#Base energy storage in Joules of: Teleporter
# Default: 5000000
# Range: 1 ~ 9223372036854775807
teleporter = 20000000
#Base energy storage in Joules of: Modification Station
# Default: 40000
# Range: 1 ~ 9223372036854775807
modificationStation = 160000
#Base energy storage in Joules of: Isotopic Centrifuge
# Default: 80000
# Range: 1 ~ 9223372036854775807
isotopicCentrifuge = 320000
#Base energy storage in Joules of: Nutritional Liquifier
# Default: 40000
# Range: 1 ~ 9223372036854775807
nutritionalLiquifier = 160000
#Base energy storage in Joules of: Nucleosynthesizer. Also defines max process rate.
# Default: 1000000000
# Range: 1 ~ 9223372036854775807
antiprotonicNucleosynthesizer = 1000000000
#Base energy storage in Joules of: Pigment Extractor
# Default: 40000
# Range: 1 ~ 9223372036854775807
pigmentExtractor = 160000
#Base energy storage in Joules of: Pigment Mixer
# Default: 80000
# Range: 1 ~ 9223372036854775807
pigmentMixer = 320000
#Base energy storage in Joules of: Painting Machine
# Default: 40000
# Range: 1 ~ 9223372036854775807
paintingMachine = 160000
#Base energy storage in Joules of: SPS Port. Also defines max output rate.
# Default: 1000000000
# Range: 1 ~ 9223372036854775807
spsPort = 2000000000
#Base energy storage in Joules of: Dimensional Stabilizer
# Default: 40000
# Range: 1 ~ 9223372036854775807
dimensionalStabilizer = 160000
