#Enable No Startup Messages module
noStartupMessagesEnabled = true
#A list of word sequences that if contained in a message will be stopped.
noStartupMessagesMessages = ["This game is using an alpha build of Ender IO", "The Mekanism Team", "Thanks for using", "Mekanism is currently in alpha", "[Warning] Ender IO is in alpha", "This pack contains Observable", "beta version of Railcraft", "Features might be missing", "Bug reports are welcome", "Sm0keySa1m0n"]
#Disable recipe advancements
disableRecipeAdvancements = true
#Enable startup ding sound
enableDingDongStartupSound = true
#Name of sound to play. Default is entity.experience_orb.pickup
dingDongSound = "entity.experience_orb.pickup"
